[package]
name = "ember_lily"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28"
ash = "0.37"
winapi = "0.3.9"